name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        GOARCH=arm go build -ldflags="-s -w" -a -installsuffix nocgo -o dist/mmotcw .
        cp -r static dist/static
        cp -r templates dist/templates
        
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: dist
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.repository == 'KeKsBoTer/mmotcw' && github.event.pull_request.merged == true
    steps: 
    - uses: actions/download-artifact@master
      with:
        name: build
        path: dist
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
