name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install build-tools
      run: sudo apt-get update &&  sudo apt-get install -y -f gcc-7-arm-linux-gnueabi gccgo-7-arm-linux-gnueabi 

    - name: Build
      run: |
        CC="arm-linux-gnueabi-gcc"  CGO_ENABLED=1 GOARCH=arm go build -o dist/mmotcw .
        cp -r static dist/static
        cp -r templates dist/templates
        
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: dist
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/download-artifact@master
      with:
        name: build
        path: dist
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
