name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: uraimo/run-on-arch-action@v2.0.5
      name: Run commands
      id: runcmd
      with:
        arch: armv7
        distro: ubuntu18.04

        # Set an output parameter `uname` for use in subsequent steps
        run: |
          uname -a
          echo ::set-output name=uname::$(uname -a)


    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        GOARCH=arm go build -o dist/mmotcw .
        cp -r static dist/static
        cp -r templates dist/templates
        
    - uses: actions/upload-artifact@master
      with:
        name: build
        path: dist
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/download-artifact@master
      with:
        name: build
        path: dist
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
